add DeliverStat && fix OctString string()
yedamao/go_cmpp pull request #1
Opened 2020-04-30 02:22 UTC by a2dict

1. 增加Deliver状态报告解析
2. 修复OctString 去补零异常

2020-04-30 10:05 UTC, yedamao commented
Thank you

2020-04-30 10:20 UTC, yedamao requested changes

2020-04-30 10:20 UTC, yedamao commented on cmpp/protocol/op_deliver.go
> +
```suggestion
// 状态报告
type Report struct {
  // SP提交短信（CMPP_SUBMIT）操作时，
  // 与SP相连的ISMG产生的Msg_Id
  MsgId          uint64
  Stat           *OctetString // 发送短信的应答结果
  SubmitTime     *OctetString
  DoneTime       *OctetString
  DestTerminalId *OctetString
  SMSCSequence   uint32
}
```
Report 已经有定义了

2020-04-30 10:20 UTC, yedamao commented on cmpp/protocol/op_deliver.go
> +}
```suggestion
func ParseReport(rawData []byte) (*Report, error) {
  if len(rawData) != 60 {
    return nil, errors.New("ParseReport: len error")
  }

  p := 0
  rpt := &Report{}

  rpt.MsgId = unpackUi64(rawData[p : p+8])
  p = p + 8
  rpt.Stat = &OctetString{Data: rawData[p : p+7]}
  p = p + 7
  rpt.SubmitTime = &OctetString{Data: rawData[p : p+10]}
  p = p + 10
  rpt.DoneTime = &OctetString{Data: rawData[p : p+10]}
  p = p + 10
  rpt.DestTerminalId = &OctetString{Data: rawData[p : p+21]}
  p = p + 21
  rpt.SMSCSequence = unpackUi32(rawData[p : p+4])
  p = p + 4

  return rpt, nil
}
```

2020-04-30 10:20 UTC, yedamao commented on cmpp/protocol/string.go
> +}
上行长短信需要处理头和拼接,所以没有放在协议包处理

2020-05-01 09:27 UTC, a2dict commented on cmpp/protocol/string.go
> +func ParseMsgContentSegment(msgFmt uint8, data []byte) (*MsgContentSegment, error) {
增加了Deliver上行消息长文本解析

2020-05-01 09:32 UTC, a2dict reviewed
变更如下：
1. DeliverStat 更换成已存在的Report
1. 更正SubmitResp ToString 命名错误
1. 增加了Deliver长文本解析

2020-05-01 09:32 UTC, a2dict commented on cmpp/protocol/op_submit.go
> +	fmt.Fprintln(&b, "--- SubmitResp ---")
这里命名错了...

2020-05-01 09:32 UTC, a2dict commented on cmpp/protocol/string.go
> +type MsgContentSegment struct {
增加了Deliver长文本解析

2020-05-20 07:39 UTC, closed without merging